name: Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build App1
        run: docker build -t app1 ./app1

      - name: Build App2
        run: docker build -t app2 ./app2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push App1
        run: |
          docker tag app1 ${{ secrets.DOCKER_USERNAME }}/2025cloud:app1
          docker push ${{ secrets.DOCKER_USERNAME }}/2025cloud:app1

      - name: Push App2
        run: |
          docker tag app2 ${{ secrets.DOCKER_USERNAME }}/2025cloud:app2
          docker push ${{ secrets.DOCKER_USERNAME }}/2025cloud:app2
